# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\milay\OneDrive\Документы\программирование(((\7taskspring\friendship.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_friendship(object):
    def setupUi(self, friendship):
        friendship.setObjectName("friendship")
        friendship.resize(400, 400)
        friendship.setMinimumSize(QtCore.QSize(400, 400))
        friendship.setMaximumSize(QtCore.QSize(400, 400))
        friendship.setStyleSheet("background-color: rgb(205, 240, 255)")
        self.listWidget = QtWidgets.QListWidget(friendship)
        self.listWidget.setGeometry(QtCore.QRect(60, 80, 291, 231))
        self.listWidget.setStyleSheet("background-color: rgb(176, 221, 255)")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)

        self.retranslateUi(friendship)
        QtCore.QMetaObject.connectSlotsByName(friendship)

    def retranslateUi(self, friendship):
        _translate = QtCore.QCoreApplication.translate
        friendship.setWindowTitle(_translate("friendship", "Dialog"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("friendship", "Мой первый друг, мой друг бесценный!\n"
"И я судьбу благословил,\n"
"Когда мой двор уединенный,\n"
"Печальным снегом занесенный,\n"
"Твой колокольчик огласил.\n"
"\n"
"Молю святое провиденье:\n"
"Да голос мой душе твоей\n"
"Дарует то же утешенье,\n"
"Да озарит он заточенье\n"
"Лучом лицейских ясных дней!"))
        self.listWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    friendship = QtWidgets.QDialog()
    ui = Ui_friendship()
    ui.setupUi(friendship)
    friendship.show()
    sys.exit(app.exec_())
