# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\milay\OneDrive\Документы\программирование(((\7taskspring\idk.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_idk(object):
    def setupUi(self, idk):
        idk.setObjectName("idk")
        idk.resize(400, 400)
        idk.setMinimumSize(QtCore.QSize(400, 400))
        idk.setMaximumSize(QtCore.QSize(400, 400))
        idk.setStyleSheet("background-color: rgb(205, 240, 255)")
        self.listWidget = QtWidgets.QListWidget(idk)
        self.listWidget.setGeometry(QtCore.QRect(90, 130, 221, 111))
        self.listWidget.setStyleSheet("background-color: rgb(176, 221, 255)\n"
"")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)

        self.retranslateUi(idk)
        QtCore.QMetaObject.connectSlotsByName(idk)

    def retranslateUi(self, idk):
        _translate = QtCore.QCoreApplication.translate
        idk.setWindowTitle(_translate("idk", "Dialog"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("idk", "He бойся в чём-то оплошать,\n"
"Hy кто из нас не ошибался?\n"
"\n"
"Куда страшнее — понимать,\n"
"Что мог, Ho даже нe пытался.."))
        self.listWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    idk = QtWidgets.QDialog()
    ui = Ui_idk()
    ui.setupUi(idk)
    idk.show()
    sys.exit(app.exec_())
