# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\milay\OneDrive\Документы\программирование(((\7taskspring\may.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_may(object):
    def setupUi(self, may):
        may.setObjectName("may")
        may.resize(400, 400)
        may.setMinimumSize(QtCore.QSize(400, 400))
        may.setMaximumSize(QtCore.QSize(400, 400))
        may.setStyleSheet("background-color: rgb(205, 240, 255)")
        self.listWidget = QtWidgets.QListWidget(may)
        self.listWidget.setGeometry(QtCore.QRect(60, 60, 281, 251))
        self.listWidget.setStyleSheet("background-color: rgb(176, 221, 255)")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)

        self.retranslateUi(may)
        QtCore.QMetaObject.connectSlotsByName(may)

    def retranslateUi(self, may):
        _translate = QtCore.QCoreApplication.translate
        may.setWindowTitle(_translate("may", "Dialog"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("may", "Вновь май нас батиком балует —\n"
"На клумбах радужность весны.\n"
"И солнце золотом рисует,\n"
"И мысли чисты и ясны.\n"
"В бездонном небе тают птицы,\n"
"Как в чае сахарный песок.\n"
"Весны последняя страница,\n"
"Май — самый красочный мазок:\n"
"Природа красками ликует\n"
"И пчёлы радостно гудят…\n"
"Вновь май нас батиком балует\n"
"И плавит сердца рафинад."))
        self.listWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    may = QtWidgets.QDialog()
    ui = Ui_may()
    ui.setupUi(may)
    may.show()
    sys.exit(app.exec_())
